
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
#如果没有使用swift 不需要使用这个
#use_frameworks!
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
#react
 pod 'React', :path => '../node_modules/react-native/'
 pod 'React-Core', :path => '../node_modules/react-native/react'

 pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
 pod 'React-DevSupport', :path => '../node_modules/react-native/react'
 pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
 pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
 pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
 pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
 pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
 pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
 pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
 pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
 pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
 pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'


pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
pod 'React-jscallinvoker', :path => '../node_modules/react-native/ReactCommon/jscallinvoker'

pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'


target 'card' do
  # Add new pods below this line
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'
  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'


  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'
  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'
  pod 'Picker', :path => '../node_modules/react-native-picker'
  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'
  pod 'ReactNativeKeyboardManager', :path => '../node_modules/react-native-keyboard-manager'
  
  #pod 'RNZipArchive', :path => '../node_modules/react-native-zip-archive'
  pod 'ReactNativeKeyboardManager', :path => '../node_modules/react-native-keyboard-manager'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'
  pod 'JCoreRN', :path => '../node_modules/jcore-react-native'
  pod 'JPushRN', :path => '../node_modules/jpush-react-native'
  pod 'sharetrace-react-native', :path => '../node_modules/sharetrace-react-native'

end
